[package]
name = "font"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
harfbuzz-wasm = { path = "../../harfbuzz-wasm"}
wasm-bindgen = "0.2.87"
tetris = { path = "../tetris" }